pipeline:
  docker:
    image: plugins/docker
    debug: true
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: arobson/aws-elasticsearch
    tags:
      - latest
      - "2.4"
    when:
      branch: master